### получение животных
GET http://localhost:8080/api/animal?page=0&size=15

### получение животных с фильтрацией
POST http://localhost:8080/api/animal/filter
Content-Type: application/json

{
  "gender": "M",
  "organizationName": "my",
  "city": "Воронеж",
  "name": "К",
  "type": "попугай"
}

### сохранение животных
POST http://localhost:8080/api/animal
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="name"

Кеша
--WebAppBoundary
Content-Disposition: form-data; name="gender"

M
--WebAppBoundary
Content-Disposition: form-data; name="type"

попугай
--WebAppBoundary
Content-Disposition: form-data; name="birthDay"

2025-03-08
--WebAppBoundary
Content-Disposition: form-data; name="breed"

Волнистый
--WebAppBoundary
Content-Disposition: form-data; name="description"

Самый красивый говорун
--WebAppBoundary
Content-Disposition: form-data; name="organizationUsername"

myanimals
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="anyFile.jpg"
Content-Type: image/jpeg

<<< ./path/to/your/anyFile.jpg
--WebAppBoundary--

### обновление животного
PUT http://localhost:8080/api/animal
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="id"

3
--WebAppBoundary
Content-Disposition: form-data; name="name"

Кеша
--WebAppBoundary
Content-Disposition: form-data; name="gender"

M
--WebAppBoundary
Content-Disposition: form-data; name="type"

попугай
--WebAppBoundary
Content-Disposition: form-data; name="birthDay"

2025-03-11
--WebAppBoundary
Content-Disposition: form-data; name="breed"

Волнистый
--WebAppBoundary
Content-Disposition: form-data; name="description"

Самый красивый говорун
--WebAppBoundary
Content-Disposition: form-data; name="organizationUsername"

myanimals
--WebAppBoundary
Content-Disposition: form-data; name="status"

ACTIVE
--WebAppBoundary

### удаление животного
DELETE http://localhost:8080/api/animal/2