### получение животных
GET http://localhost:8080/api/animal?page=0&size=15

### получение животных с фильтрацией
POST http://localhost:8080/api/animal/filter
Content-Type: application/json

{
  "gender": "M",
  "organizationName": "my",
  "city": "Воронеж",
  "name": "К",
  "type": "попугай"
}

### сохранение животных
POST http://localhost:8080/api/animal
Content-Type: application/json

{
  "name": "Кеша",
  "gender": "M",
  "type": "попугай",
  "birthDay": "2025-03-08",
  "breed": "Волнистый",
  "description": "Самый красивый говорун",
  "organizationUsername": "myanimals",
  "attributes": {
    "Окрас": "Синий"
  }
}

### обновление животного
PUT http://localhost:8080/api/animal
Content-Type: application/json

{
  "id": 5,
  "name": "Кеша",
  "gender": "M",
  "status": "ACTIVE",
  "type": "попугай",
  "birthDay": "2025-03-08",
  "breed": "Волнистый",
  "description": "Самый красивый говорун",
  "organizationUsername": "myanimals",
  "attributes": {
    "Окрас": "голубой"
  }
}

### удаление животного
DELETE http://localhost:8080/api/animal/2