FROM openjdk:8-jdk-alpine
VOLUME /tmp
ADD build/libs/backend-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT exec java $JAVA_OPTS -jar /app.jar
COPY src/main/resources/minio/minioPolicy.json /app/minioPolicy.json

EXPOSE 8080