server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-binding-errors: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME:animals}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    drop-first: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  jwtSecret: MegaLargeSigningSecretKeyForDemoApplicationMegaLargeSigningSecretKeyForDemoApplication
  jwtExpirationMs: 86400000

minio:
  url: http://${MINIO_HOST}:${MINIO_PORT}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
