server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/animals
    username: admin
    password: pass
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    drop-first: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  jwtSecret: MegaLargeSigningSecretKeyForDemoApplicationMegaLargeSigningSecretKeyForDemoApplication
  jwtExpirationMs: 86400000

minio:
  url: http://minio:9000
  accessKey: minioadmin
  secretKey: minioadmin
