spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/animals
    username: admin
    password: pass
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    drop-first: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: false

minio:
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
